Add in a kraken follows endpoint implementation
muxy/twitchgo pull request #1
Opened 2020-05-13 22:09 UTC by albert-wang

2020-05-13 23:07 UTC, cwc approved these changes
Approved with go fmt 👍

2020-05-13 23:07 UTC, cwc commented on follow.go
> +    "fmt"
Needs a go fmt?

2020-05-14 01:47 UTC, camr requested changes

2020-05-14 01:47 UTC, camr commented on twitch.go
> +func NewTwitchClient(clientID string, token string) TwitchClient {
This is an API change. I forgot Go doesn't have optional arguments 🙄 

What are your thoughts on a new `NewTwitchClientWithOptions` that takes some amount of optional arguments including an `http.Client` and `bearer token`?

2020-05-14 14:03 UTC, cwc commented on twitch.go
> +func NewTwitchClient(clientID string, token string) TwitchClient {
OAuth tokens are required to do anything with the API now right? So all existing projects using the lib are broken and need updating anyway. The backwards-compatible func would have no use.

2020-05-14 20:51 UTC, closed without merging